### ISSUE TITLE
Setup error on Win10

### ISSUE THREAD

**Issue by JosephSBoyle** [JoakimEdin/medical-coding-reproducibility#1]
Hi, I'm getting a setup error on windows when executing step 2 fromin the readme.
I think the command should be `pip install -e .` but the instruction says `pip install . -e` which is not a valid pip command as far as I know.

Here's the trace from within my anaconda terminal:![image](https://github.com/JoakimEdin/medical-coding-reproducibility/assets/48555120/efde3015-0f57-41de-b28f-9301050fb6e2)

Edit updated to a screenshot as text was malformatted.

**Comment by JoakimEdin** [comment]
Thank you! It was an error in the requirement file. The issue has been fixed!
