### ISSUE TITLE
OSError: Read-only File System Error While Running prepare_mimiciii_mullenbach.py

### ISSUE THREAD

**Issue by Ahmed-Mortadi** [JoakimEdin/medical-coding-reproducibility#4]
I encountered an error while trying to run the prepare_data/prepare_mimiciii_mullenbach.py script. The error message I received is as follows:
OSError: [Errno 30] Read-only file system: '/content/MIMIC_Dataset/mimic-iii-clinical-database-1.4/NOTEEVENTS.feather'

Directory Structure:
Here is the directory structure that contains both the MIMIC-III and MIMIC-IV datasets:

├── 📁 MIMIC_Dataset
│   ├── 📁 mimic-iv-2.2
│   │   ├── 📄 CHANGELOG.txt
│   │   ├── 📄 LICENSE.txt
│   │   ├── 📄 SHA256SUMS.txt
│   │   ├── 📁 hosp
│   │   │   ├── 📄 omr.csv.gz
│   │   │   ├── 📄 microbiologyevents.csv.gz
│   │   │   ├── 📄 d_icd_procedures.csv.gz
│   │   │   ├── 📄 admissions.csv.gz
│   │   │   ├── 📄 d_labitems.csv.gz
│   │   │   ├── 📄 drgcodes.csv.gz
│   │   │   ├── 📄 patients.csv.gz
│   │   │   ├── 📄 hcpcsevents.csv.gz
│   │   │   ├── 📄 d_hcpcs.csv.gz
│   │   │   ├── 📄 d_icd_diagnoses.csv.gz
│   │   │   ├── 📄 diagnoses_icd.csv.gz
│   │   │   ├── 📄 provider.csv.gz
│   │   │   ├── 📄 transfers.csv.gz
│   │   │   ├── 📄 pharmacy.csv.gz
│   │   │   ├── 📄 services.csv.gz
│   │   │   ├── 📄 procedures_icd.csv.gz
│   │   │   ├── 📄 prescriptions.csv.gz
│   │   │   ├── 📄 emar.csv.gz
│   │   │   ├── 📄 emar_detail.csv.gz
│   │   │   ├── 📄 poe.csv.gz
│   │   │   ├── 📄 poe_detail.csv.gz
│   │   │   └── 📄 labevents.csv.gz
│   │   └── 📁 icu
│   │       ├── 📄 caregiver.csv.gz
│   │       ├── 📄 d_items.csv.gz
│   │       ├── 📄 datetimeevents.csv.gz
│   │       ├── 📄 procedureevents.csv.gz
│   │       ├── 📄 outputevents.csv.gz
│   │       ├── 📄 chartevents.csv.gz
│   │       ├── 📄 ingredientevents.csv.gz
│   │       ├── 📄 inputevents.csv.gz
│   │       └── 📄 icustays.csv.gz
│   └── 📁 mimic-iii-clinical-database-1.4
│       ├── 📄 ADMISSIONS.csv.gz
│       ├── 📄 CAREGIVERS.csv.gz
│       ├── 📄 CALLOUT.csv.gz
│       ├── 📄 D_ICD_DIAGNOSES.csv.gz
│       ├── 📄 checksum_md5_zipped.txt
│       ├── 📄 D_CPT.csv.gz
│       ├── 📄 D_LABITEMS.csv.gz
│       ├── 📄 checksum_md5_unzipped.txt
│       ├── 📄 D_ITEMS.csv.gz
│       ├── 📄 DIAGNOSES_ICD.csv.gz
│       ├── 📄 D_ICD_PROCEDURES.csv.gz
│       ├── 📄 DRGCODES.csv.gz
│       ├── 📄 DATETIMEEVENTS.csv.gz
│       ├── 📄 ICUSTAYS.csv.gz
│       ├── 📄 CPTEVENTS.csv.gz
│       ├── 📄 CHARTEVENTS.csv.gz
│       ├── 📄 INPUTEVENTS_MV.csv.gz
│       ├── 📄 INPUTEVENTS_CV.csv.gz
│       ├── 📄 MICROBIOLOGYEVENTS.csv.gz
│       ├── 📄 LABEVENTS.csv.gz
│       ├── 📄 OUTPUTEVENTS.csv.gz
│       ├── 📄 PATIENTS.csv.gz
│       ├── 📄 NOTEEVENTS.csv.gz
│       ├── 📄 SERVICES.csv.gz
│       ├── 📄 PROCEDUREEVENTS_MV.csv.gz
│       ├── 📄 README.md
│       ├── 📄 PROCEDURES_ICD.csv.gz
│       ├── 📄 TRANSFERS.csv.gz
│       ├── 📄 PRESCRIPTIONS.csv.gz
│       ├── 📄 LICENSE.txt
│       └── 📄 SHA256SUMS.txt
└── 📄 Allow cookies

Questions:

1. I'm not sure if my directory structure is appropriate for running the code. Can you please review it and confirm whether it's set up correctly?

2. The "README.md" also mentions (in the "Prepare MIMIC-IV" section) changing the variable DOWNLOAD_DIRECTORY_MIMICIV_NOTE to the path of the downloaded data. However, I'm unsure where to find this path in my MIMIC-IV dataset. Could you provide guidance on where to locate this path?

**Comment by JoakimEdin** [comment]
It sounds like the folder has a read only permission. Are you using linux or max os? If yes, try `ls -l` to show the permissions of the folders. Send me the output!

**Comment by Ahmed-Mortadi** [comment]
Indeed, it was a permission issue tied to my method of accessing the dataset in Google Colab. Specifically, the shortcut to the dataset in Google Drive had read-only permissions, leading to the "Read-only File System" error.

To resolve this, I took the step of transferring the dataset files to the local disk within Colab. This action eliminated this error.

I'm grateful for your assistance. Thank you.
