### ISSUE TITLE
MIMIC-IV notes

### ISSUE THREAD

**Issue by LeiGong0125Carrot** [JoakimEdin/medical-coding-reproducibility#9]
Hello,

I am wondering how you concatenate the notes and ICD-10 code inside the MIMIC-IV dataset since the MIMIC-IV Note dataset only contains the subject ID and notes. I do not see that the MIMIC-IV dataset contains the related variable. Could you please figure this out for me?

**Comment by JoakimEdin** [comment]
There should be a column in MIMIC-IV NOTE called hadm_id. It stands for hospital admission ID. Is it not in your downloaded data?
